# Generated by Django 5.0 on 2024-09-11 09:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictExpenditure',
            fields=[
                ('dict_expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_expense_type_id', models.IntegerField()),
                ('dict_expenditure_name', models.TextField()),
            ],
            options={
                'db_table': 'dict_expenditure',
            },
        ),
        migrations.CreateModel(
            name='DictSecChapter',
            fields=[
                ('dict_sec_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_sec_chapter_name', models.TextField()),
            ],
            options={
                'db_table': 'dict_sec_chapter',
            },
        ),
        migrations.CreateModel(
            name='EpcCalculation',
            fields=[
                ('epc_calculation_ind', models.AutoField(primary_key=True, serialize=False)),
                ('epc_calculation_mrid', models.CharField(max_length=36, null=True)),
                ('epc_calculation_before_ded', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Расчет УНЦ',
                'verbose_name_plural': 'Расчеты УНЦ',
                'db_table': 'epc_calculation',
            },
        ),
        migrations.CreateModel(
            name='ExpensesToEpcMap',
            fields=[
                ('expenses_to_epc_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenses_to_epc_map_name', models.TextField()),
                ('expenses_to_epc_map_epc', models.TextField()),
            ],
            options={
                'db_table': 'expenses_to_epc_map',
            },
        ),
        migrations.CreateModel(
            name='InvestProject',
            fields=[
                ('invest_project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('project_code', models.TextField()),
                ('dict_project_type_id', models.IntegerField(null=True)),
                ('dict_project_status_id', models.IntegerField(null=True)),
                ('invest_project_type', models.IntegerField(null=True)),
                ('invest_project_mrid', models.CharField(max_length=36, null=True)),
                ('invest_project_version', models.IntegerField(null=True)),
                ('invest_project_unc_forecast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invest_project_create_dttm', models.DateTimeField(null=True)),
                ('invest_project_update_dttm', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Инвестиционный проект',
                'verbose_name_plural': 'Инвестиционные проекты',
                'db_table': 'invest_project',
            },
        ),
        migrations.CreateModel(
            name='LocalCostEstimate',
            fields=[
                ('local_cost_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_cost_estimate_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Локальная смета',
                'verbose_name_plural': 'Локальные сметы',
                'db_table': 'local_cost_estimates',
            },
        ),
        migrations.CreateModel(
            name='ObjectCostEstimate',
            fields=[
                ('object_cost_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_cost_estimate_code', models.TextField()),
            ],
            options={
                'verbose_name': 'Объектная смета',
                'verbose_name_plural': 'Объектные сметы',
                'db_table': 'object_cost_estimates',
            },
        ),
        migrations.CreateModel(
            name='TempTableUNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.TextField()),
                ('project_name', models.TextField()),
                ('name_unc', models.TextField()),
                ('name_object', models.TextField()),
                ('voltage', models.TextField()),
                ('TX', models.TextField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.TextField()),
                ('unc_code', models.TextField()),
            ],
            options={
                'db_table': 'temp_table_unc',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EpcCosts',
            fields=[
                ('epc_costs_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_cost_epc_id', models.TextField()),
                ('dict_cost_epc_table_id', models.IntegerField(null=True)),
                ('name_unc', models.TextField()),
                ('name_object', models.TextField()),
                ('voltage', models.TextField()),
                ('TX', models.TextField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.TextField()),
                ('is_check', models.BooleanField(default=False, verbose_name='Проверено')),
                ('description', models.TextField(blank=True, null=True)),
                ('epc_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epccalculation')),
            ],
            options={
                'verbose_name': 'Расценка УНЦ',
                'verbose_name_plural': 'Расценки УНЦ',
                'db_table': 'epc_costs',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_expenditure_id', models.IntegerField(null=True)),
                ('expense_nme', models.TextField(null=True)),
                ('quarter', models.TextField()),
                ('construction_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость строительных работ')),
                ('installation_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость монтажных работ')),
                ('equipment_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря')),
                ('other_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость прочих затрат')),
                ('total_cost', models.TextField(blank=True, null=True, verbose_name='Общая сметная стоимость')),
                ('is_check', models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено')),
                ('description', models.TextField(blank=True, null=True)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter')),
                ('local_cost_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.localcostestimate')),
                ('object_cost_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate')),
            ],
            options={
                'verbose_name': 'Затрата',
                'verbose_name_plural': 'Затраты',
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='ExpensesByEpc',
            fields=[
                ('expenses_by_epc_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_typical_epc_work_id', models.IntegerField(null=True)),
                ('dict_budgeting_id', models.IntegerField(null=True)),
                ('expenses_by_epc_nme', models.TextField(null=True)),
                ('is_check', models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено')),
                ('description', models.TextField(blank=True, null=True)),
                ('epc_costs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epccosts')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expenses')),
                ('expenses_to_epc_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap')),
            ],
            options={
                'verbose_name': 'Затраты по УНЦ',
                'verbose_name_plural': 'Затраты по УНЦ',
                'db_table': 'expenses_by_epc',
            },
        ),
        migrations.CreateModel(
            name='LocalEstimateData',
            fields=[
                ('parsed_local_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(verbose_name='Номер строки')),
                ('row_data', models.JSONField(verbose_name='Данные строки в формате JSON')),
                ('local_cost_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='myapp.localcostestimate')),
            ],
            options={
                'verbose_name': 'Данные парсинга локальной сметы',
                'verbose_name_plural': 'Данные парсинга локальных смет',
                'db_table': 'local_estimate_data',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type_id', models.IntegerField(null=True)),
                ('dict_region_id', models.IntegerField(null=True)),
                ('dict_work_type_id', models.IntegerField(null=True)),
                ('dict_substaion_type_id', models.IntegerField(null=True)),
                ('start_up_complex_id', models.IntegerField(null=True)),
                ('dict_regions_economic_zone_id', models.IntegerField(null=True)),
                ('object_name', models.TextField(null=True)),
                ('object_mrid', models.CharField(max_length=36, null=True)),
                ('object_is_analogue', models.BooleanField(null=True)),
                ('object_create_dttm', models.DateTimeField(null=True)),
                ('object_update_dttm', models.DateTimeField(null=True)),
                ('invest_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.investproject')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': 'object',
            },
        ),
        migrations.AddField(
            model_name='epccosts',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.object'),
        ),
        migrations.AddField(
            model_name='epccalculation',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_calculations', to='myapp.object'),
        ),
        migrations.CreateModel(
            name='AtypicalExpenses',
            fields=[
                ('atypical_expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_atypical_expenses_id', models.IntegerField(null=True)),
                ('epc_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epccalculation')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.object')),
            ],
            options={
                'verbose_name': 'Ненормированные затраты',
                'verbose_name_plural': 'Ненормированные затраты',
                'db_table': 'atypical_expenses',
            },
        ),
        migrations.CreateModel(
            name='ObjectAnalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.TextField()),
                ('project_name', models.TextField()),
                ('object_costEstimate_id', models.TextField()),
                ('local_costEstimate_id', models.TextField()),
                ('expenses_name', models.TextField()),
                ('quarter', models.TextField()),
                ('construction_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость строительных работ')),
                ('installation_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость монтажных работ')),
                ('equipment_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря')),
                ('other_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость прочих затрат')),
                ('total_cost', models.TextField(blank=True, null=True, verbose_name='Общая сметная стоимость')),
                ('unc_code', models.TextField()),
                ('name_unc', models.TextField()),
                ('name_object', models.TextField()),
                ('voltage', models.TextField()),
                ('TX', models.TextField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.TextField()),
                ('matched_keyword', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_check', models.BooleanField(default=False, verbose_name='Проверено')),
                ('description', models.TextField(blank=True, null=True)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter')),
                ('key_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap')),
            ],
            options={
                'db_table': 'object_analog',
            },
        ),
        migrations.AddField(
            model_name='localcostestimate',
            name='object_cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.CreateModel(
            name='SummaryEstimateCalculation',
            fields=[
                ('summary_estimate_calculation_id', models.AutoField(primary_key=True, serialize=False)),
                ('sum_est_calc_mrid', models.CharField(max_length=36, null=True)),
                ('sum_est_calc_before_ded', models.BooleanField(null=True)),
                ('invest_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.investproject')),
            ],
            options={
                'verbose_name': 'Сводная смета расчета',
                'verbose_name_plural': 'Сводные сметы расчетов',
                'db_table': 'summary_estimate_calculation',
            },
        ),
        migrations.AddField(
            model_name='objectcostestimate',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AddField(
            model_name='localcostestimate',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.TextField()),
                ('object_costEstimate_id', models.TextField(blank=True, null=True)),
                ('local_costEstimate_id', models.TextField(blank=True, null=True)),
                ('expenses_name', models.TextField()),
                ('quarter', models.TextField(blank=True, null=True)),
                ('construction_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость строительных работ')),
                ('installation_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость монтажных работ')),
                ('equipment_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря')),
                ('other_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость прочих затрат')),
                ('total_cost', models.TextField(blank=True, null=True, verbose_name='Общая сметная стоимость')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter')),
            ],
            options={
                'db_table': 'temp_table',
            },
        ),
        migrations.CreateModel(
            name='TempTableLocal',
            fields=[
                ('parsed_local_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(verbose_name='Номер строки')),
                ('row_data', models.JSONField(verbose_name='Данные строки в формате JSON')),
                ('temp_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='myapp.temptable')),
            ],
            options={
                'verbose_name': 'Данные парсинга локальной сметы',
                'verbose_name_plural': 'Данные парсинга локальных смет',
                'db_table': 'temp_table_local',
            },
        ),
        migrations.CreateModel(
            name='TempTableССКUNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_keyword', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap')),
                ('temp_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.temptable')),
                ('temp_table_unc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.temptableunc')),
            ],
            options={
                'db_table': 'temp_table_cck_unc',
            },
        ),
    ]
