# Generated by Django 5.0 on 2024-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestoepcmap',
            name='expenses_to_epc_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
