# Generated by Django 5.0 on 2024-08-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectanalog',
            name='key_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
        ),
        migrations.AddField(
            model_name='temptableсскunc',
            name='key_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
            preserve_default=False,
        ),
    ]
