# Generated by Django 5.0 on 2024-08-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryestimatecalculation',
            name='object',
        ),
        migrations.AddField(
            model_name='summaryestimatecalculation',
            name='invest_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.investproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='local_cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.localcostestimate'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='object_cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.AlterField(
            model_name='expensesbyepc',
            name='expense_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.expenses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensesbyepc',
            name='expenses_to_epc_map_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localcostestimate',
            name='object_cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='local_costEstimate_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
