# Generated by Django 5.0 on 2024-11-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localestimatedatasort',
            name='local_estimate_data_count',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='localestimatedatasort',
            name='local_estimate_data_unit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='epccalculation',
            name='object_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epc_calculations', to='myapp.object'),
        ),
        migrations.AlterField(
            model_name='epccosts',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dict_sec_chapter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter'),
        ),
        migrations.AlterField(
            model_name='expensesbyepc',
            name='epc_costs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epccosts'),
        ),
        migrations.AlterField(
            model_name='expensesbyepc',
            name='expense_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expenses'),
        ),
        migrations.AlterField(
            model_name='expensesbyepc',
            name='expenses_to_epc_map_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
        ),
        migrations.AlterField(
            model_name='localcostestimate',
            name='object_cost_estimate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.AlterField(
            model_name='localcostestimate',
            name='summary_estimate_calculation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AlterField(
            model_name='localestimatedatasort',
            name='local_cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_sort_data', to='myapp.localcostestimate'),
        ),
        migrations.AlterField(
            model_name='object',
            name='invest_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.investproject'),
        ),
        migrations.AlterField(
            model_name='objectcostestimate',
            name='summary_estimate_calculation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AlterField(
            model_name='summaryestimatecalculation',
            name='invest_project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.investproject'),
        ),
    ]
