# Generated by Django 5.0 on 2024-10-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstimateDataSort',
            fields=[
                ('sort_local_estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_estimate_data_code', models.TextField(null=True)),
                ('local_estimate_data_part', models.TextField(null=True)),
                ('local_estimate_data_name', models.TextField(null=True)),
                ('local_estimate_data_type', models.TextField(null=True)),
                ('local_cost_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_sort_data', to='myapp.localcostestimate')),
            ],
            options={
                'verbose_name': 'Данные сортировки локальной сметы',
                'verbose_name_plural': 'Данные сортировки локальных смет',
                'db_table': 'local_estimate_data_sort',
            },
        ),
    ]
