# Generated by Django 5.0 on 2024-08-11 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictExpenditure',
            fields=[
                ('dict_expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_expense_type_id', models.IntegerField()),
                ('dict_expenditure_name', models.TextField()),
            ],
            options={
                'db_table': 'dict_expenditure',
            },
        ),
        migrations.CreateModel(
            name='DictSecChapter',
            fields=[
                ('dict_sec_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_sec_chapter_name', models.TextField()),
            ],
            options={
                'db_table': 'dict_sec_chapter',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_expenditure_id', models.IntegerField()),
                ('expense_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_name', models.TextField()),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='ExpensesToEpcMap',
            fields=[
                ('expenses_to_epc_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenses_to_epc_map_name', models.TextField()),
                ('expenses_to_epc_map_epc', models.TextField()),
            ],
            options={
                'db_table': 'expenses_to_epc_map',
            },
        ),
        migrations.CreateModel(
            name='LocalCostEstimate',
            fields=[
                ('local_cost_estimate_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'local_cost_estimate',
            },
        ),
        migrations.CreateModel(
            name='ObjectCostEstimate',
            fields=[
                ('object_cost_estimate_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'object_cost_estimate',
            },
        ),
        migrations.CreateModel(
            name='SummaryEstimateCalculation',
            fields=[
                ('summary_estimate_calculation_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('sum_est_calc_mrid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sum_est_calc_before_ded', models.BooleanField()),
            ],
            options={
                'db_table': 'summary_estimate_calculation',
            },
        ),
        migrations.CreateModel(
            name='ExpensesByEpc',
            fields=[
                ('expenses_by_epc_id', models.AutoField(primary_key=True, serialize=False)),
                ('epc_costs_id', models.IntegerField()),
                ('dict_typical_epc_work_id', models.IntegerField()),
                ('dict_budgeting_id', models.IntegerField()),
                ('expenses_by_epc_name', models.TextField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expense')),
                ('expenses_to_epc_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap')),
            ],
            options={
                'db_table': 'expenses_by_epc',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='local_cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.localcostestimate'),
        ),
        migrations.AddField(
            model_name='localcostestimate',
            name='object_cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.AddField(
            model_name='expense',
            name='object_cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate'),
        ),
        migrations.AddField(
            model_name='objectcostestimate',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AddField(
            model_name='localcostestimate',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
        migrations.AddField(
            model_name='expense',
            name='summary_estimate_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.summaryestimatecalculation'),
        ),
    ]
