# Generated by Django 5.0 on 2024-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expensestoepcmap_expenses_to_epc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestoepcmap',
            name='expenses_to_epc_voltage_marker',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
