# Generated by Django 5.0 on 2024-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_localestimatedatasort'),
    ]

    operations = [
        migrations.AddField(
            model_name='localestimatedatasort',
            name='local_estimate_data_type_code',
            field=models.TextField(null=True),
        ),
    ]
