# Generated by Django 5.0 on 2024-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_summaryestimatecalculation_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investproject',
            name='project_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investproject',
            name='project_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
