# Generated by Django 5.0 on 2024-08-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dictexpenditure_dictsecchapter_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expenses_name', models.TextField()),
                ('construction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость строительных работ')),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость монтажных работ')),
                ('equipment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря')),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость прочих затрат')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая сметная стоимость')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter')),
                ('local_costEstimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.localcostestimate')),
                ('object_costEstimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.objectcostestimate')),
            ],
            options={
                'db_table': 'temp_table',
            },
        ),
    ]
