# Generated by Django 5.0 on 2024-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_investproject_project_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesbyepc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesbyepc',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
