# Generated by Django 5.0 on 2024-08-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_temptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='local_costEstimate_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='object_costEstimate_id',
            field=models.TextField(),
        ),
    ]
