# Generated by Django 5.0 on 2024-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_temptable_local_costestimate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptable',
            name='project_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temptable',
            name='quarter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
