# Generated by Django 5.0 on 2024-09-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_expensesbyepc_description_expensesbyepc_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesbyepc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expensesbyepc',
            name='is_check',
        ),
        migrations.AddField(
            model_name='epccosts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epccosts',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
