# Generated by Django 5.0 on 2024-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_expensestoepcmap_expenses_to_epc_voltage_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestoepcmap',
            name='expenses_to_epc_voltage_marker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
