# Generated by Django 5.0 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_temptable_project_id_temptable_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTableUNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.TextField()),
                ('name_unc', models.TextField()),
                ('name_object', models.TextField()),
                ('voltage', models.TextField()),
                ('TX', models.TextField()),
                ('unit', models.TextField()),
                ('unc_code', models.TextField()),
            ],
            options={
                'db_table': 'temp_table_unc',
            },
        ),
    ]
