# Generated by Django 5.0 on 2024-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_expensesbyepc_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='is_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено'),
        ),
    ]
