# Generated by Django 5.0 on 2024-08-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_temptableunc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTableССКUNC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_keyword', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('temp_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.temptable')),
                ('temp_table_unc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.temptableunc')),
            ],
            options={
                'db_table': 'temp_table_cck_unc',
            },
        ),
    ]
