# Generated by Django 5.0 on 2024-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_expenses_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesbyepc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesbyepc',
            name='is_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено'),
        ),
    ]
