# Generated by Django 5.0 on 2024-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_temptableсскunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptableunc',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
