# Generated by Django 5.0 on 2024-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_parsedlocalestimatedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParsedLocalEstimateData',
            new_name='LocalEstimateData',
        ),
    ]
