# Generated by Django 5.0 on 2024-08-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_temptable_construction_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptable',
            name='construction_cost',
        ),
        migrations.AddField(
            model_name='temptable',
            name='conconstruction_cost',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость строительных работ'),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='equipment_cost',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря'),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='installation_cost',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость монтажных работ'),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='other_cost',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость прочих затрат'),
        ),
        migrations.AlterField(
            model_name='temptable',
            name='total_cost',
            field=models.TextField(blank=True, null=True, verbose_name='Общая сметная стоимость'),
        ),
    ]
