# Generated by Django 5.0 on 2024-08-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_temptable_construction_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temptable',
            old_name='conconstruction_cost',
            new_name='construction_cost',
        ),
    ]
