# Generated by Django 5.0 on 2024-09-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_temptablelocal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localestimatedata',
            table='local_estimate_data',
        ),
    ]
