# Generated by Django 5.0 on 2024-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_conconstruction_cost_temptable_construction_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAnalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.TextField()),
                ('project_name', models.TextField()),
                ('object_costEstimate_id', models.TextField()),
                ('local_costEstimate_id', models.TextField()),
                ('expenses_name', models.TextField()),
                ('quarter', models.TextField()),
                ('construction_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость строительных работ')),
                ('installation_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость монтажных работ')),
                ('equipment_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость оборудования, мебели, инвентаря')),
                ('other_cost', models.TextField(blank=True, null=True, verbose_name='Стоимость прочих затрат')),
                ('total_cost', models.TextField(blank=True, null=True, verbose_name='Общая сметная стоимость')),
                ('unc_code', models.TextField()),
                ('name_unc', models.TextField()),
                ('name_object', models.TextField()),
                ('voltage', models.TextField()),
                ('TX', models.TextField()),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.TextField()),
            ],
            options={
                'db_table': 'object_analog',
            },
        ),
    ]
