# Generated by Django 5.0 on 2024-08-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_objectanalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectanalog',
            name='chapter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.dictsecchapter'),
            preserve_default=False,
        ),
    ]
