# Generated by Django 5.0 on 2024-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_temptableunc_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectanalog',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectanalog',
            name='matched_keyword',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
