# Generated by Django 5.0 on 2024-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_objectanalog_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectanalog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectanalog',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
