# Generated by Django 5.0 on 2024-08-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_objectanalog_description_objectanalog_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectanalog',
            name='key_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
            preserve_default=False,
        ),
    ]
