# Generated by Django 5.0 on 2024-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_objectanalog_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptableсскunc',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
