# Generated by Django 5.0 on 2024-08-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_temptableсскunc_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptableсскunc',
            name='is_check',
        ),
        migrations.AddField(
            model_name='temptableсскunc',
            name='key_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='myapp.expensestoepcmap'),
            preserve_default=False,
        ),
    ]
