# Generated by Django 5.0 on 2024-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_objectanalog_key_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='quarter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
