# Generated by Django 5.0 on 2024-08-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_temptable_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='object_costEstimate_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
